name:                search-engine-pagerank
version:             0.1.0.0
github:              "githubuser/search-engine-pagerank"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/search-engine-pagerank#readme>

dependencies:
- prettyprinter
- split
- tagsoup
- containers
- raw-strings-qq
- with-utf8
- regex-posix
- regex-tdfa ^>= 1.3.1
- pandoc
- vector
- bytestring
- text
- aeson
- base >= 4.7 && < 5


library:
  source-dirs: src

executables:
  search-engine-pagerank-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - search-engine-pagerank

tests:
  search-engine-pagerank-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - search-engine-pagerank
